# Generated by Django 2.2.4 on 2020-01-05 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_auto_20200105_1140'),
    ]

    operations = [
        migrations.RenameField(
            model_name='song',
            old_name='music_file_link',
            new_name='song_file_link',
        ),
        migrations.RenameField(
            model_name='song',
            old_name='music_video_link',
            new_name='song_music_video_link',
        ),
        migrations.RemoveField(
            model_name='artiste',
            name='other_title_2',
        ),
        migrations.RemoveField(
            model_name='song',
            name='music_file',
        ),
        migrations.RemoveField(
            model_name='song',
            name='music_snippet',
        ),
        migrations.RemoveField(
            model_name='song',
            name='music_video',
        ),
        migrations.RemoveField(
            model_name='song',
            name='person2',
        ),
        migrations.RemoveField(
            model_name='song',
            name='person3',
        ),
        migrations.RemoveField(
            model_name='song',
            name='person4',
        ),
        migrations.RemoveField(
            model_name='song',
            name='person5',
        ),
        migrations.AddField(
            model_name='album',
            name='album_art',
            field=models.ImageField(blank=True, default='images/no-img.jpg', upload_to='album_art_images/'),
        ),
        migrations.AddField(
            model_name='artiste',
            name='album_art_thumbnail',
            field=models.ImageField(blank=True, default='images/no-img.jpg', upload_to='album_art_thumbnails/'),
        ),
        migrations.AddField(
            model_name='artiste',
            name='artiste_art',
            field=models.ImageField(blank=True, default='images/no-img.jpg', upload_to='artiste_art_images/'),
        ),
        migrations.AddField(
            model_name='song',
            name='song_file',
            field=models.FileField(blank=True, default='audio/def.mp3', upload_to='song_audio/'),
        ),
        migrations.AddField(
            model_name='song',
            name='song_music_video',
            field=models.FileField(blank=True, default='audio/def.mp3', upload_to='song_music_video/'),
        ),
        migrations.AddField(
            model_name='song',
            name='song_snippet',
            field=models.FileField(blank=True, default='audio/def.mp3', upload_to='song_audio_snippet/'),
        ),
        migrations.AlterField(
            model_name='artiste',
            name='other_title_1',
            field=models.CharField(blank=True, max_length=25, verbose_name='What did you Contribute? Piano, Composer? Beats? Smoke?'),
        ),
        migrations.AlterField(
            model_name='song',
            name='is_explicit',
            field=models.BooleanField(default=True, verbose_name='Check if the song contain explicit content'),
        ),
        migrations.AlterField(
            model_name='song',
            name='song_album_art',
            field=models.ImageField(blank=True, default='images/no-img.jpg', upload_to='song_art_images/'),
        ),
        migrations.AlterField(
            model_name='song',
            name='song_art',
            field=models.ImageField(blank=True, default='images/no-img.jpg', upload_to='song_art_images/'),
        ),
    ]
