# Generated by Django 4.1.5 on 2023-01-09 05:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artiste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=51, verbose_name='Artiste Name')),
                ('title', models.IntegerField(choices=[(1, 'Singer'), (2, 'Rapper'), (3, 'Vocals'), (4, 'Piano'), (5, 'Beats Maker')], default='1')),
                ('other_title_1', models.CharField(blank=True, max_length=25, verbose_name='What did you Contribute? Piano, Composer? Beats? Smoke?')),
                ('other_title_multiple', models.CharField(blank=True, max_length=1000, verbose_name='Enter Tittle comma seperetad')),
                ('artiste_art', models.ImageField(blank=True, default='images/no-img.jpg', upload_to='artiste_art_images/')),
                ('album_art_thumbnail', models.ImageField(blank=True, default='images/no-img.jpg', upload_to='album_art_thumbnails/')),
                ('firstName', models.CharField(max_length=25, verbose_name='First Name')),
                ('lastName', models.CharField(max_length=25, verbose_name='Last Name')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date Created')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date Updated')),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song_name', models.CharField(max_length=51, verbose_name='Song Name')),
                ('is_explicit', models.BooleanField(default=True, verbose_name='Check if the song contain explicit content')),
                ('music_genre', models.IntegerField(choices=[(1, 'hipop'), (2, 'afro'), (3, 'indie'), (4, 'k-pop'), (5, 'pop')], default='1')),
                ('lyrics', models.TextField()),
                ('description', models.TextField()),
                ('song_file', models.FileField(blank=True, default='audio/def.mp3', upload_to='song_audio/')),
                ('song_snippet', models.FileField(blank=True, default='audio/def.mp3', upload_to='song_audio_snippet/')),
                ('song_file_link', models.URLField(blank=True)),
                ('song_music_video', models.FileField(blank=True, default='audio/def.mp3', upload_to='song_music_video/')),
                ('song_music_video_link', models.URLField(blank=True)),
                ('song_art', models.ImageField(blank=True, default='images/no-img.jpg', upload_to='song_art_images/')),
                ('song_album_art', models.ImageField(blank=True, default='images/no-img.jpg', upload_to='song_art_images/')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date Created')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date Updated')),
                ('additional_information', models.TextField(default='None')),
                ('artiste', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='song', to='music.artiste')),
                ('artiste_fetures', models.ManyToManyField(blank=True, related_name='song_features', to='music.artiste')),
                ('person1', models.ManyToManyField(blank=True, related_name='song_creator_1', to='music.artiste')),
            ],
        ),
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('album_name', models.CharField(max_length=51, verbose_name='Album Name')),
                ('album_art', models.ImageField(blank=True, default='images/no-img.jpg', upload_to='album_art_images/')),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date Created')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date Updated')),
                ('artiste', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='album', to='music.artiste')),
                ('songs', models.ManyToManyField(related_name='songs', to='music.song')),
            ],
        ),
    ]
