# Generated by Django 2.2.4 on 2020-01-05 07:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('album_name', models.CharField(max_length=51, verbose_name='Album Name')),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date Created')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date Updated')),
            ],
        ),
        migrations.CreateModel(
            name='Artiste',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=51, verbose_name='Artiste Name')),
                ('firstName', models.CharField(max_length=25, verbose_name='First Name')),
                ('lastName', models.CharField(max_length=25, verbose_name='Last Name')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date Created')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date Updated')),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song_name', models.CharField(max_length=51, verbose_name='Song Name')),
                ('lyrics', models.TextField()),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date Created')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date Updated')),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.Album')),
                ('artiste', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='song', to='music.Artiste')),
                ('artiste_fetures', models.ManyToManyField(related_name='song_features', to='music.Artiste')),
            ],
        ),
        migrations.AddField(
            model_name='album',
            name='artiste',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='album', to='music.Artiste'),
        ),
        migrations.AddField(
            model_name='album',
            name='songs',
            field=models.ManyToManyField(related_name='songs', to='music.Song'),
        ),
    ]
