# Generated by Django 2.2.4 on 2020-01-05 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_auto_20200105_0814'),
    ]

    operations = [
        migrations.AddField(
            model_name='artiste',
            name='other_title_1',
            field=models.CharField(blank=True, max_length=25, verbose_name='Enter Tittle as an Artiste'),
        ),
        migrations.AddField(
            model_name='artiste',
            name='other_title_2',
            field=models.CharField(blank=True, max_length=25, verbose_name='Enter Tittle as an Artiste'),
        ),
        migrations.AddField(
            model_name='artiste',
            name='other_title_multiple',
            field=models.CharField(blank=True, max_length=1000, verbose_name='Enter Tittle comma seperetad'),
        ),
        migrations.AddField(
            model_name='artiste',
            name='title',
            field=models.IntegerField(choices=[(1, 'Singer'), (2, 'Rapper'), (2, 'Vocals'), (2, 'Piano'), (2, 'Beats Maker')], default='1'),
        ),
        migrations.AddField(
            model_name='song',
            name='additional_information',
            field=models.TextField(default='None'),
        ),
        migrations.AddField(
            model_name='song',
            name='is_explicit',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='song',
            name='music_file',
            field=models.FileField(blank=True, default='audio/def.mp3', upload_to='audio/'),
        ),
        migrations.AddField(
            model_name='song',
            name='music_file_link',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='song',
            name='music_genre',
            field=models.IntegerField(choices=[(1, 'hipop'), (2, 'afro'), (3, 'indie'), (4, 'k-pop'), (5, 'pop')], default='1'),
        ),
        migrations.AddField(
            model_name='song',
            name='music_snippet',
            field=models.FileField(blank=True, default='audio/def.mp3', upload_to='audio/'),
        ),
        migrations.AddField(
            model_name='song',
            name='music_video',
            field=models.FileField(blank=True, default='audio/def.mp3', upload_to='audio/'),
        ),
        migrations.AddField(
            model_name='song',
            name='music_video_link',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='song',
            name='person1',
            field=models.ManyToManyField(blank=True, related_name='song_creator_1', to='music.Artiste'),
        ),
        migrations.AddField(
            model_name='song',
            name='person2',
            field=models.ManyToManyField(blank=True, related_name='song_creator_2', to='music.Artiste'),
        ),
        migrations.AddField(
            model_name='song',
            name='person3',
            field=models.ManyToManyField(blank=True, related_name='song_creator_3', to='music.Artiste'),
        ),
        migrations.AddField(
            model_name='song',
            name='person4',
            field=models.ManyToManyField(blank=True, related_name='song_creator_4', to='music.Artiste'),
        ),
        migrations.AddField(
            model_name='song',
            name='person5',
            field=models.ManyToManyField(blank=True, related_name='song_creator_5', to='music.Artiste'),
        ),
        migrations.AddField(
            model_name='song',
            name='song_album_art',
            field=models.ImageField(blank=True, default='images/no-img.jpg', upload_to='images/'),
        ),
        migrations.AddField(
            model_name='song',
            name='song_art',
            field=models.ImageField(blank=True, default='images/no-img.jpg', upload_to='images/'),
        ),
    ]
